### ISSUE TITLE
Jcenter is shutting down

### ISSUE THREAD

**Issue by csagariw** [wajahatkarim3/RoomExplorer#2]
Since JCentre is going to shut down, this library needs to be uploaded to maven or other suitable library hosting platforms.
More on this article https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by wajahatkarim3** [comment]
Hello @csagariw, Thank you for reporting this issue. I am aware of it and I am in the process of moving all my libraries to maven central soon.
